/*Date : 23 sept 2023 saturday
1st prblm => how to make any random number to do not show the random number that is already been printed in any other
variable within the same range
for e.g.           after importing the the random class , and let the random generator name is r

                      int i = r.nextInt(); //here if there is random number range is from 0 to 5 and suppose if it is generating number 2
                                                      // then we want ,other coming variables should not print the same random number which is
                                                      // already been generated by the previous variables

          if i is generating 2 then next variable should generate any one of the numbers 1,3,4,5 and if it has generated 4 then next to it should generate
from numbers 1, 3,5 and so on...
0
2nd prblm => CWH_28_PracSet_no_6 Que no 1 Harry Bhaiya method , Que no.2
3rd prblm => rough_work_2 Que no. income tax calculator


































 */